apiVersion: batch/v1
kind: Job
metadata:
  name: ds-ai
  namespace: group5
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: ds-ai
        image: group5se4ai22/repo_mlflow_group5se4ai22
        command: ["python", "train.py"]
      restartPolicy: Never