stages:
  - build
  - deploy

build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${REGISTRY_USER}" "${REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/services/backend/Dockerfile"
      --destination "${REGISTRY_IMAGE}:${COMMIT_TAG}"
  rules:
    - if: $COMMIT_TAG

deploy-backend:      
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - cd services/backend
    - kubectl config set clusters.k8s.certificate-authority-data $K8S_CERTIFICATE 
    - kubectl config set clusters.k8s.server $K8S_SERVER
    - kubectl config set users.ci-user.token $K8S_TOKEN
    - kubectl config set-context ci-k8s --cluster=k8s --user=ci-user --namespace=group5
    - kubectl config use-context ci-k8s
    - kubectl apply -f backend.yaml