stages:
  - build
  - push
  - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - cd services/backend
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PW docker.io
    - docker build -f Dockerfile -t index.docker.io/group5se4ai22/repo_backend_group5se4ai22 .
    - docker push index.docker.io/group5se4ai22/repo_backend_group5se4ai22
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

push_to_dockerhub:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - cd services/backend
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PW docker.io
    - docker pull index.docker.io/group5se4ai22/repo_backend_group5se4ai22

    - docker login -u=$DOCKER_USER -p=$DOCKER_PW docker.io
    - docker tag index.docker.io/group5se4ai22/repo_backend_group5se4ai22 index.docker.io/group5se4ai22/repo_backend_group5se4ai22:latest
    - docker push group5se4ai22/repo_backend_group5se4ai22:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy-backend:      
  stage: deploy
  script:
    - cd services/backend
    - kubectl config set clusters.k8s.certificate-authority-data $K8S_CERTIFICATE 
    - kubectl config set clusters.k8s.server $K8S_SERVER
    - kubectl config set users.ci-user.token $K8S_TOKEN
    - kubectl config set-context ci-k8s --cluster=k8s --user=ci-user --namespace=group5
    - kubectl config use-context ci-k8s
    - kubectl apply -f backend.yaml