apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-fastapi-deployment
  labels:
    app: ds-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-fastapi
  template:
    metadata:
      labels:
        app: ds-fastapi
    spec:
      containers:
        - name: ds-fastapi
          image: group5se4ai22/repo_backend_group5se4ai22:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: pg-secrets
                key: pg-database-url
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: pg-secrets
                key: pg-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: ds-fastapi-service
spec:
  selector:
    app: ds-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
