apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper
spec:
  schedule: "35 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: group5se4ai22/repo_scraper_group5se4ai22:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure