apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper
spec:
  template:
    spec:
      schedule: "00 13 * * 1"
      containers:
      - name: scraper
        image: group5se4ai22/repo_scraper_group5se4ai22:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure