apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-vue-deployment
  labels:
    app: ds-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-vue
  template:
    metadata:
      labels:
        app: ds-vue
    spec:
      containers:
        - name: ds-vue-container
          image: group5se4ai22/repo_frontend_group5se4ai22:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ds-vue-service
spec:
  selector:
    app: ds-vue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080